
CREATE TABLE TRUONG_CUSTOMER (
    CUSTOMER_ID NUMBER NOT NULL,
    NAME VARCHAR2(255,BYTE) NOT NULL,
    ADDRESS VARCHAR2(255, BYTE),
    WEBSITE VARCHAR2(255, BYTE),
    CREDIT_LIMIT NUMBER(6,2)
);