-- SELECT * FROM ONE TABLE ---
SELECT * FROM employees;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;

-- SELECT SPECIFIC COLUMNS in ONE TABLE--
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE
FROM EMPLOYEES;

SELECT CUSTOMER_ID, NAME, ADDRESS
FROM CUSTOMERS;

SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, SALESMAN_ID
FROM ORDERS;

SELECT PRODUCT_ID, PRODUCT_NAME, DESCRIPTION
FROM PRODUCTS;

-- SELECT COLUMN ALIAS, TABLE ALIAS --
SELECT 
    EMPLOYEE_ID AS MA_NHAN_VIEN,
    FIRST_NAME AS TEN_GOI,
    LAST_NAME AS TEH_NO,
    EMAIL AS THU_DIEN_TU,
    HIRE_DATE AS NGAY_NHAN_VIEC
FROM EMPLOYEES;

SELECT 
    CUSTOMER_ID AS MA_KHACH_HANG,
    NAME AS TEN_KHACH_HANG,
    ADDRESS AS DIA_CHI_KHACH_HANG
FROM CUSTOMERS;

SELECT
    ORDER_ID AS MA_DON_HANG,
    CUSTOMER_ID AS MA_KHACH_HANG,
    ORDER_DATE AS NGAY_DAT_HANG,
    SALESMAN_ID AS NGUOI_BAN
FROM ORDERS;

SELECT
    PRODUCT_ID AS MA_SAN_PHAM,
    PRODUCT_NAME AS TEN_SAN_PHAM,
    DESCRIPTION AS MO_TA
FROM PRODUCTS;

-- SELECT DISTINCT --
SELECT DISTINCT JOB_TITLE
FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME
FROM EMPLOYEES;

-- WHERE Clause AND OR BETWEEN EQUAL, GREATER, LESS --
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 28;

SELECT * FROM EMPLOYEES
WHERE EMAIL = 'abigail.palmer@example.com'
AND PHONE = '650.505.4876';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME = 'Elliot'
AND LAST_NAME = 'Cooper';

SELECT * FROM CUSTOMERS
WHERE CREDIT_LIMIT > 1000;

SELECT * FROM CUSTOMERS
WHERE CREDIT_LIMIT >= 2000;

SELECT * FROM CUSTOMERS
WHERE CREDIT_LIMIT < 3200;

SELECT * FROM CUSTOMERS
WHERE CREDIT_LIMIT <= 2400;

SELECT * FROM ORDERS
WHERE ORDER_DATE > '01-JAN-17';

SELECT * FROM ORDERS
WHERE ORDER_DATE BETWEEN '01-JAN-17' AND '01-JAN-19';

-- WILDCARD --
SELECT * FROM CUSTOMERS
WHERE NAME LIKE 'American%';

SELECT * FROM CUSTOMERS
WHERE NAME LIKE '%corp';

SELECT * FROM CUSTOMERS
WHERE NAME LIKE '%bank%'
OR NAME LIKE 'america';

SELECT * FROM CUSTOMERS
WHERE NAME LIKE 'I%'
AND LENGTH(NAME) = 3;

SELECT * FROM CUSTOMERS
WHERE NAME LIKE '%P'
AND LENGTH(NAME /*CH VARCHAR2*/) = 2;

SELECT * FROM CUSTOMERS
WHERE NAME LIKE '_n%';

-- IN --
SELECT * FROM PRODUCTS
WHERE PRODUCT_NAME IN ('G.Skill Ripjaws V Series',
                     'ASRock X99 Extreme11', 
                     'Intel Xeon E5-2697 V2');

SELECT * FROM PRODUCTS
WHERE PRODUCT_NAME NOT IN ('Corsair Vengeance LPX',
                        'Corsair Dominator Platinum',
                        'G.Skill Ripjaws V Series',
                        'Kingston',
                        'Supermicro X10SDV-8C-TLN4F',
                        'Intel DP35DPM',
                        'Asus X99-E-10G WS',
                        'Asus ROG MAXIMUS IX EXTREME');