
CREATE TABLE truong_oils (
    NGAY_THANG DATE,
    LOAI VARCHAR2(200),
    GIABAN NUMBER,
    TON_KHO NUMBER,
    GIA_TRI NUMBER,
    CUA_HANG VARCHAR2(200)
);

INSERT INTO truong_oils VALUES ('8/31/2020')