
--1--
SELECT
    CTG.CATEGORY_NAME,
    C.CUSTOMER_ID,
    C.NAME,
    SUM(O.TOTAL),
    CON.PHONE
FROM PRODUCT_CATEGORIES CTG
JOIN PRODUCTS P
    ON CTG.CATEGORY_ID = P.CATEGORY_ID
JOIN ORDER_ITEMS OI
    ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O
    ON O.ORDER_ID = OI.ORDER_ID
JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN CONTACTS CON
    ON C.CUSTOMER_ID = CON.CONTACT_ID
GROUP BY CTG.CATEGORY_NAME, C.CUSTOMER_ID, C.NAME, CON.PHONE
ORDER BY SUM(O.TOTAL) DESC;


--2--
SELECT *
FROM PRODUCTS P
JOIN INVENTORIES I
    ON P.PRODUCT_ID = I.PRODUCT_ID
JOIN WAREHOUSES W
    ON I.WAREHOUSE_ID = W.WAREHOUSE_ID
JOIN LOCATIONS L
    ON L.LOCATION_ID = W.LOCATION_ID
JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID
