
--1--
SELECT C.CUSTOMER_ID, NAME, COUNT(*)
FROM ORDERS O
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    1=1
    AND STATUS = 'Shipped'
GROUP BY C.CUSTOMER_ID, NAME
HAVING COUNT(*) > 3;

--2--
SELECT C.CUSTOMER_ID, NAME, STATUS, COUNT(*)
FROM ORDERS O
JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
    1=1
    AND STATUS = 'Canceled'
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY C.CUSTOMER_ID, NAME, STATUS
HAVING COUNT(*) > 0;

--3--
SELECT O.CUSTOMER_ID, NAME, COUNT(OI.PRODUCT_ID)
FROM ORDERS O
JOIN ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE O.STATUS='Shipped'
GROUP BY O.CUSTOMER_ID, NAME
HAVING COUNT(OI.PRODUCT_ID) > 10;

--4--
SELECT O.CUSTOMER_ID, NAME, O.ORDER_DATE, SUM(OI.QUANTITY)
FROM ORDERS O
JOIN ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    1=1
    AND O.STATUS = 'Pending'
    AND O.ORDER_DATE > TO_DATE('10/02/2017', 'DD/MM/YYYY')
GROUP BY O.CUSTOMER_ID, NAME, O.ORDER_DATE
HAVING SUM(OI.QUANTITY) > 50;

--5--
-- Lấy ra báo cáo chi tiết sản phẩm theo các tiêu chí sau: Tổng số lượng bán,
-- Tổng giá trị bán, trung bình giá trị bán (Nếu sp chưa từng bán thì mặc định là 0)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    NVL(SUM(OI.QUANTITY), 0),
    NVL(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0),
    NVL(ROUND(AVG(OI.QUANTITY * OI.UNIT_PRICE), 2), 0)
FROM PRODUCTS P
LEFT JOIN ORDER_ITEMS OI
    ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY P.PRODUCT_ID;


--6--
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    COUNT(OI.ORDER_ID) AS SL_DON_HANG
FROM ORDER_ITEMS OI
JOIN PRODUCTS P
    ON OI.PRODUCT_ID = P.PRODUCT_ID
JOIN ORDERS O
    ON O.ORDER_ID = OI.ORDER_ID
WHERE
    1=1
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY COUNT(OI.ORDER_ID) DESC, P.PRODUCT_ID ASC
FETCH FIRST 10 ROWS ONLY;

--7--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    COUNT(O.ORDER_ID)
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
    ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O
    ON O.ORDER_ID = OI.ORDER_ID
WHERE
    1=1
    AND STATUS IN ('Canceled', 'Pending')
    AND O.ORDER_DATE >= TO_DATE('02/10/2016', 'DD/MM/YYYY')
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY COUNT(O.ORDER_ID) DESC, P.PRODUCT_ID ASC
FETCH FIRST 20 ROWS ONLY;

--8--
--9--
SELECT
    PC.CATEGORY_ID,
    PC.CATEGORY_NAME,
    COUNT(O.ORDER_ID) AS SO_LUONG_DON
FROM PRODUCT_CATEGORIES PC
JOIN PRODUCTS P
    ON PC.CATEGORY_ID = P.CATEGORY_ID
JOIN ORDER_ITEMS OI
    ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID
WHERE
    1=1
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
    AND EXTRACT(MONTH FROM O.ORDER_DATE) BETWEEN 1 AND 3
GROUP BY 
    PC.CATEGORY_ID, 
    PC.CATEGORY_NAME
ORDER BY PC.CATEGORY_ID ASC;

--10--
SELECT 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME, 
    PC.CATEGORY_NAME, 
    SUM(I.QUANTITY)
FROM PRODUCTS P
LEFT JOIN INVENTORIES I
    ON P.PRODUCT_ID = I.PRODUCT_ID
JOIN PRODUCT_CATEGORIES PC
    ON P.CATEGORY_ID = PC.CATEGORY_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, PC.CATEGORY_NAME
HAVING SUM(I.QUANTITY) IS NULL OR SUM(QUANTITY) = 0
ORDER BY P.PRODUCT_ID;

--11--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    W.WAREHOUSE_NAMES,
    SUM(I.QUANTITY)
FROM PRODUCTS P
LEFT JOIN INVENTORIES I
    ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN WAREHOUSES W
    ON I.WAREHOUSE_ID = W.WAREHOUSE_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, W.WAREHOUSE_NAMES
ORDER BY P.PRODUCT_ID;

--13--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    W.WAREHOUSE_NAMES,
    L.ADDRESS,
    SUM(I.QUANTITY)
FROM INVENTORIES I 
LEFT JOIN PRODUCTS P 
    ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN WAREHOUSES W
    ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
LEFT JOIN LOCATIONS L
    ON L.LOCATION_ID = W.LOCATION_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, W.WAREHOUSE_NAMES, L.ADDRESS
ORDER BY P.PRODUCT_ID;

--14--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    W.WAREHOUSE_NAMES,
    L.ADDRESS,
    C.COUNTRY_NAME,
    SUM(I.QUANTITY)
FROM PRODUCTS P
LEFT JOIN INVENTORIES I
    ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN WAREHOUSES W
    ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
LEFT JOIN LOCATIONS L
    ON L.LOCATION_ID = W.LOCATION_ID
LEFT JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, W.WAREHOUSE_NAMES, L.ADDRESS, C.COUNTRY_NAME
ORDER BY P.PRODUCT_ID;

--15--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    W.WAREHOUSE_NAMES,
    L.ADDRESS,
    C.COUNTRY_NAME,
    R.REGION_NAME,
    SUM(I.QUANTITY)
FROM PRODUCTS P
LEFT JOIN INVENTORIES I
    ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN WAREHOUSES W
    ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
LEFT JOIN LOCATIONS L
    ON L.LOCATION_ID = W.LOCATION_ID
LEFT JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID
LEFT JOIN REGIONS R
    ON C.REGION_ID = R.REGION_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, W.WAREHOUSE_NAMES, L.ADDRESS, C.COUNTRY_NAME, R.REGION_NAME
ORDER BY P.PRODUCT_ID;

--16--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    W.WAREHOUSE_NAMES,
    SUM(I.QUANTITY)
FROM PRODUCTS P
JOIN INVENTORIES I 
    ON P.PRODUCT_ID = I.PRODUCT_ID
JOIN WAREHOUSES W
    ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, W.WAREHOUSE_NAMES
ORDER BY SUM(I.QUANTITY) DESC
FETCH FIRST 100 ROWS ONLY;

--17--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    C.COUNTRY_NAME,
    SUM(I.QUANTITY)
FROM INVENTORIES I 
LEFT JOIN PRODUCTS P 
    ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN WAREHOUSES W
    ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
LEFT JOIN LOCATIONS L
    ON L.LOCATION_ID = W.LOCATION_ID
LEFT JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, W.WAREHOUSE_NAMES, C.COUNTRY_NAME
ORDER BY SUM(I.QUANTITY) ASC
FETCH FIRST 100 ROWS ONLY;

--18--
SELECT 
    E.EMPLOYEE_ID,
    E.FIRST_NAME, 
    E.LAST_NAME,
    SUM(O.TOTAL)
FROM EMPLOYEES E 
JOIN ORDERS O
    ON E.EMPLOYEE_ID = O.SALESMAN_ID
GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME
ORDER BY SUM(O.TOTAL) DESC
FETCH FIRST 10 ROWS ONLY;

--19--
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    COUNT(O.ORDER_ID)
FROM EMPLOYEES E 
LEFT JOIN ORDERS O
    ON E.EMPLOYEE_ID = O.SALESMAN_ID
WHERE
    1=1
    AND EXTRACT(YEAR FROM O.ORDER_DATE) BETWEEN 2016 AND 2017
GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME

--20--
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    EXTRACT(MONTH FROM O.ORDER_DATE) AS THANG,
    COUNT(O.ORDER_ID)
FROM EMPLOYEES E
LEFT JOIN ORDERS O
    ON E.EMPLOYEE_ID = O.SALESMAN_ID
WHERE
    1=1
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
    AND O.STATUS = 'Canceled'
GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, EXTRACT(MONTH FROM O.ORDER_DATE)
ORDER BY THANG ASC;

--21--
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    SUM(OI.QUANTITY)
FROM EMPLOYEES E 
LEFT JOIN ORDERS O
    ON E.EMPLOYEE_ID = O.SALESMAN_ID
LEFT JOIN ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
WHERE
    1=1
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2016
    AND EXTRACT(MONTH FROM O.ORDER_DATE) BETWEEN 1 AND 4
GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME;