
--1--
SELECT C.CUSTOMER_ID, NAME, COUNT(*)
FROM ORDERS O
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    1=1
    AND STATUS = 'Shipped'
GROUP BY C.CUSTOMER_ID, NAME
HAVING COUNT(*) > 3;

--2--
SELECT C.CUSTOMER_ID, NAME, STATUS, COUNT(*)
FROM ORDERS O
JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
    1=1
    AND STATUS = 'Canceled'
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY C.CUSTOMER_ID, NAME, STATUS
HAVING COUNT(*) > 2;

--3--
SELECT O.CUSTOMER_ID, NAME, SUM(OI.QUANTITY)
FROM ORDERS O
JOIN ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY O.CUSTOMER_ID, NAME
HAVING SUM(OI.QUANTITY) > 10;

--4--
SELECT O.CUSTOMER_ID, NAME, O.ORDER_DATE, OI.QUANTITY
FROM ORDERS O
JOIN ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    1=1
    AND OI.QUANTITY > 50
    AND O.STATUS = 'Pending'
    AND O.ORDER_DATE > TO_DATE('10/02/2017', 'DD/MM/YYYY');

--5--
-- Lấy ra báo cáo chi tiết sản phẩm theo các tiêu chí sau: Tổng số lượng bán,
-- Tổng giá trị bán, trung bình giá trị bán (Nếu sp chưa từng bán thì mặc định là 0)

--6--
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    COUNT(OI.ORDER_ID) AS SL_DON_HANG
FROM ORDER_ITEMS OI
JOIN PRODUCTS P
    ON OI.PRODUCT_ID = P.PRODUCT_ID
JOIN ORDERS O
    ON O.ORDER_ID = OI.ORDER_ID
WHERE
    1=1
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY COUNT(OI.ORDER_ID) DESC

--7--
