
--1--
SELECT C.CUSTOMER_ID, NAME, COUNT(*)
FROM ORDERS O
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    1=1
    AND STATUS = 'Shipped'
GROUP BY C.CUSTOMER_ID, NAME
HAVING COUNT(*) > 3;

--2--
SELECT C.CUSTOMER_ID, NAME, STATUS, COUNT(*)
FROM ORDERS O
JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
    1=1
    AND STATUS = 'Canceled'
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY C.CUSTOMER_ID, NAME, STATUS
HAVING COUNT(*) > 2;

--3--
SELECT O.CUSTOMER_ID, NAME, SUM(OI.QUANTITY)
FROM ORDERS O
JOIN ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY O.CUSTOMER_ID, NAME
HAVING SUM(OI.QUANTITY) > 10;

--4--
SELECT O.CUSTOMER_ID, NAME, O.ORDER_DATE, OI.QUANTITY
FROM ORDERS O
JOIN ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    1=1
    AND OI.QUANTITY > 50
    AND O.STATUS = 'Pending'
    AND O.ORDER_DATE > TO_DATE('10/02/2017', 'DD/MM/YYYY');

--5--
-- Lấy ra báo cáo chi tiết sản phẩm theo các tiêu chí sau: Tổng số lượng bán,
-- Tổng giá trị bán, trung bình giá trị bán (Nếu sp chưa từng bán thì mặc định là 0)

--6--
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    COUNT(OI.ORDER_ID) AS SL_DON_HANG
FROM ORDER_ITEMS OI
JOIN PRODUCTS P
    ON OI.PRODUCT_ID = P.PRODUCT_ID
JOIN ORDERS O
    ON O.ORDER_ID = OI.ORDER_ID
WHERE
    1=1
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY COUNT(OI.ORDER_ID) DESC;

--7--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.STANDARD_COST,
    P.LIST_PRICE,
    SUM(OI.QUANTITY)
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
    ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O
    ON O.ORDER_ID = OI.ORDER_ID
WHERE
    1=1
    AND (STATUS = 'Pending' 
        OR STATUS = 'Canceled')
    AND O.ORDER_DATE > TO_DATE('02/10/2016', 'DD/MM/YYYY')
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.STANDARD_COST, P.LIST_PRICE
ORDER BY SUM(OI.QUANTITY) DESC
FETCH FIRST 20 ROWS ONLY;

--8--
--9--
SELECT
    PC.CATEGORY_ID,
    PC.CATEGORY_NAME,
    EXTRACT(MONTH FROM O.ORDER_DATE) AS MONTH,
    EXTRACT(YEAR FROM O.ORDER_DATE) AS YEAR,
    COUNT(O.ORDER_ID) AS SO_LUONG_DON
FROM PRODUCT_CATEGORIES PC
JOIN PRODUCTS P
    ON PC.CATEGORY_ID = P.CATEGORY_ID
JOIN ORDER_ITEMS OI
    ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID
WHERE
    1=1
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
    AND EXTRACT(MONTH FROM O.ORDER_DATE) BETWEEN 1 AND 3
GROUP BY 
    PC.CATEGORY_ID, 
    PC.CATEGORY_NAME,
    EXTRACT(MONTH FROM O.ORDER_DATE),
    EXTRACT(YEAR FROM O.ORDER_DATE)
ORDER BY MONTH ASC, PC.CATEGORY_ID ASC;

--10--
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, PC.CATEGORY_NAME, I.QUANTITY
FROM PRODUCTS P
JOIN INVENTORIES I
    ON P.PRODUCT_ID = I.PRODUCT_ID
JOIN PRODUCT_CATEGORIES PC
    ON P.CATEGORY_ID = PC.CATEGORY_ID
WHERE
    1=1
    AND I.QUANTITY = 0

--11--

--12--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    W.WAREHOUSE_NAMES,
    I.QUANTITY
FROM INVENTORIES I 
JOIN PRODUCTS P
    ON P.PRODUCT_ID = I.PRODUCT_ID
JOIN WAREHOUSES W
    ON I.WAREHOUSE_ID = W.WAREHOUSE_ID
WHERE
    I.QUANTITY > 0;


--13--
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    W.WAREHOUSE_NAMES,
    L.ADDRESS,
    I.QUANTITY
FROM INVENTORIES I 
JOIN PRODUCTS P 
    ON P.PRODUCT_ID = I.PRODUCT_ID
JOIN WAREHOUSES W
    ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
JOIN LOCATIONS L
    ON L.LOCATION_ID = W.LOCATION_ID
WHERE
    I.QUANTITY > 0;

--14--
