--15--
SELECT
    PRODUCT_ID,
    INITCAP(PRODUCT_NAME)
FROM PRODUCTS;

--16--
SELECT
    PRODUCT_NAME,
    LTRIM(DESCRIPTION, 'Speed:')
FROM PRODUCTS
WHERE
    1=1
    AND DESCRIPTION LIKE 'Speed%';

--17--
SELECT
    PRODUCT_NAME,
    SUBSTR(PRODUCT_NAME, 1, 5)
FROM PRODUCTS
WHERE PRODUCT_NAME LIKE 'Intel%';

--18--
SELECT *
FROM PRODUCTS
WHERE LENGTH(PRODUCT_NAME) < 12;

--19--
SELECT
    CUSTOMER_ID,
    SUM(TOTAL),
    EXTRACT(YEAR FROM ORDER_DATE)
FROM ORDERS
WHERE 
    1=1
    AND STATUS='Shipped'
GROUP BY CUSTOMER_ID, EXTRACT(YEAR FROM ORDER_DATE)
ORDER BY CUSTOMER_ID, EXTRACT(YEAR FROM ORDER_DATE);

--20--
SELECT
    CUSTOMER_ID,
    SUM(TOTAL)
FROM ORDERS
WHERE
    1=1
    AND STATUS='Pending'
    AND ADD_MONTHS(ORDER_DATE, 3) >= TO_DATE('2017/03/14', 'YYYY/MM/DD')
    AND ORDER_DATE <= TO_DATE('2017/03/14', 'YYYY/MM/DD')
GROUP BY CUSTOMER_ID
ORDER BY CUSTOMER_ID, SUM(TOTAL);

--21--
SELECT
    SALESMAN_ID,
    SUM(TOTAL),
    MAX(TOTAL),
    MIN(TOTAL),
    EXTRACT(MONTH FROM ORDER_DATE) AS THANG,
    EXTRACT(YEAR FROM ORDER_DATE) AS NAM
FROM ORDERS
WHERE STATUS='Canceled'
GROUP BY SALESMAN_ID, EXTRACT(YEAR FROM ORDER_DATE), EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY NAM, THANG, SALESMAN_ID;