
--1.1 Using MERGE--
CREATE TABLE TD_EMP_LOAD AS
SELECT * FROM EMP_LOAD;

MERGE INTO TD_EMP_LOAD E1
USING (
    SELECT 
        EMP_ID,
        FIRST_NAME,
        LAST_NAME,
        START_DATE,
        END_DATE,
        CASE WHEN
            END_DATE >= START_DATE THEN 0
        ELSE 1 END STATUS
    FROM EMP_LOAD
) E2
ON (E1.EMP_ID = E2.EMP_ID)

WHEN MATCHED THEN
    UPDATE
    SET
        E1.END_DATE = E2.END_DATE,
        E1.STATUS = 0
    WHERE E2.END_DATE >= E1.START_DATE

WHEN NOT MATCHED THEN
    INSERT (
        E1.EMP_ID,
        E1.FIRST_NAME,
        E1.LAST_NAME,
        E1.START_DATE,
        E1.STATUS
    ) VALUES (
        E2.EMP_ID,
        E2.FIRST_NAME,
        E2.LAST_NAME,
        E2.START_DATE,
        E2.STATUS
    );

--2--
CREATE TABLE TD_CUST_LOAD AS
SELECT * FROM CUSTOMER;
ALTER TABLE TD_CUST_LOAD ADD RANK_TRANS NUMBER;
ALTER TABLE TD_CUST_LOAD ADD UPDATE_DATE DATE;

MERGE INTO TD_CUST_LOAD c1
USING (
    SELECT
        C.CUST_ID,
        COUNT(1) AS AVL,
        DENSE_RANK() OVER (ORDER BY COUNT(1) DESC) AS RANK_TRANS,
        TRUNC(SYSDATE) AS UPDATE_DATE
    FROM CUSTOMER C 
    JOIN ACCOUNT A
        ON C.CUST_ID = A.CUST_ID
    JOIN ACC_TRANSACTION AT
        ON AT.ACCOUNT_ID = A.ACCOUNT_ID
    GROUP BY C.CUST_ID, TRUNC(SYSDATE)
) c2
ON (c1.CUST_ID = c2.CUST_ID)
WHEN MATCHED THEN
    UPDATE
    SET c1.RANK_TRANS = c2.RANK_TRANS
    WHERE c1.RANK_TRANS != c2.RANK_TRANS
WHEN NOT MATCHED THEN
    INSERT (c1.CUST_ID, c1.RANK_TRANS, c1.UPDATE_DATE)
    VALUES (c2.CUST_ID, c2.RANK_TRANS, c2.UPDATE_DATE);


--3--
WITH ACCOUNT_RANK AS (
    SELECT
        ACCOUNT_ID,
        CUST_ID,
        SUM(AVAIL_BALANCE) AS BALANCE,
        ROW_NUMBER() OVER (PARTITION BY CUST_ID ORDER BY SUM(AVAIL_BALANCE) DESC) AS RANK
    FROM ACCOUNT 
    GROUP BY ACCOUNT_ID, CUST_ID
)
SELECT *
FROM ACCOUNT_RANK
WHERE RANK <= 2;

--4--
SELECT
    TMP.YEAR,
    TMP.NAME,
    TMP.YEAR_SALES,
    TMP.PREVIOUS_SALE_YEAR,
    NVL(ROUND((TMP.YEAR_SALES - TMP.PREVIOUS_SALE_YEAR) / NULLIF (
        TMP.YEAR_SALES, 0
    ), 3) * 100, 0) PCT_CHG
FROM (
    SELECT
        EXTRACT(YEAR FROM OPEN_DATE) AS YEAR,
        NAME,
        SUM(AVAIL_BALANCE) YEAR_SALES,
        LAG(SUM(AVAIL_BALANCE), 1, 0) OVER (PARTITION BY NAME ORDER BY NAME) PREVIOUS_SALE_YEAR
    FROM PRODUCT P
    JOIN ACCOUNT A 
        ON P.PRODUCT_CD = A.PRODUCT_CD
    WHERE EXTRACT(YEAR FROM OPEN_DATE) BETWEEN 2000 AND 2003
    GROUP BY EXTRACT(YEAR FROM OPEN_DATE), NAME
) TMP;